# Timing / clock
- ros_topic_name: '/clock'
  gz_topic_name: '/clock'
  ros_type_name: 'rosgraph_msgs/msg/Clock'
  gz_type_name:  'gz.msgs.Clock'
  direction: GZ_TO_ROS

# Joint states (from Ignition joint state publisher)
- ros_topic_name: '/joint_states'
  gz_topic_name: '/model/husky/joint_states'
  ros_type_name: 'sensor_msgs/msg/JointState'
  gz_type_name:  'ignition.msgs.Model'
  direction: GZ_TO_ROS

# Odometry (from Ignition odometry system)
- ros_topic_name: '/odometry'
  gz_topic_name: '/model/husky/odometry'
  ros_type_name: 'nav_msgs/msg/Odometry'
  gz_type_name:  'ignition.msgs.Odometry'
  direction: GZ_TO_ROS

# IMU
- ros_topic_name: '/imu'
  gz_topic_name: '/model/husky/imu'
  ros_type_name: 'sensor_msgs/msg/Imu'
  gz_type_name:  'ignition.msgs.IMU'
  direction: GZ_TO_ROS

# Camera image
- ros_topic_name: '/camera/image'
  gz_topic_name: '/model/husky/camera/image'
  ros_type_name: 'sensor_msgs/msg/Image'
  gz_type_name:  'ignition.msgs.Image'
  direction: GZ_TO_ROS

# 2D LiDAR
- ros_topic_name: '/scan'
  gz_topic_name: '/model/husky/scan'
  ros_type_name: 'sensor_msgs/msg/LaserScan'
  gz_type_name:  'ignition.msgs.LaserScan'
  direction: GZ_TO_ROS
