frequency: 30.0
two_d_mode: true
publish_tf: true

map_frame: map
odom_frame: odom
base_link_frame: base_link
world_frame: odom   # standard Nav2 setup: world = odom for this EKF

# Replace these with your actual topics:
odom0: /odom                 # or /model/husky/odometry, /wheel/odometry, etc.
odom0_differential: false

imu0: /imu/data              # if you have IMU; else comment these 3 lines out
imu0_differential: false
imu0_remove_gravity: true

# Optional: which fields to fuse (sensible defaults)
odom0_config: [true,  true,  false,
               false, false, true,
               true,  true,  false,
               false, false, true,
               false, false, false]
imu0_config:  [false, false, false,
               false, false, true,
               false, false, false,
               false, false, true,
               false, false, false]
